nginx:
  image: "nginx:1.9"
  ports:
    - 80:80
    - 443:443
  links:
    - app:app
  environment:
    - TZ=Europe/Moscow
  volumes:
    - ./nginx/ssl:/etc/nginx/ssl:ro
    - ./nginx/logs:/var/log/nginx
    - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./nginx/html/:/etc/nginx/html:ro
app:
  image: "petrpopov/failure-service"
  environment:
    - SPRING_PROFILES_ACTIVE=prod
    - TZ=Europe/Moscow
  restart: always
  links:
    - mongodb:mongo
  volumes:
    - ./app:/var/log/app
mongodb:
  image: bitnami/mongodb
  ports:
    - 27018:27017
    - 28019:28017
  environment:
    - TZ=Europe/Moscow
    - MONGODB_USER=failure
    - MONGODB_PASSWORD=dsn4JKns3
    - MONGODB_DATABASE=failure
  volumes:
    - ./db:/opt/bitnami/mongodb/data
 # command: --smallfiles --rest --auth
